package com.bazi.ttmk.model;
// Generated Jan 29, 2020, 7:04:22 PM by Hibernate Tools 4.3.5.Final


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Fazi generated by hbm2java
 */
@Entity
@Table(name="fazi",
        uniqueConstraints = @UniqueConstraint(columnNames={"id_turnir", "id_kategorija", "opis_faza"}),
        schema = "project")
public class Fazi  implements java.io.Serializable {


     private FaziId id;
     private String opisFaza;
     private Integer brojFaza;

    public Fazi() {
    }

	
    public Fazi(FaziId id, String opisFaza) {
        this.id = id;
        this.opisFaza = opisFaza;
    }
    public Fazi(FaziId id, String opisFaza, Integer brojFaza) {
       this.id = id;
       this.opisFaza = opisFaza;
       this.brojFaza = brojFaza;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="redenBroj", column=@Column(name="reden_broj", nullable=false) ), 
        @AttributeOverride(name="idTurnir", column=@Column(name="id_turnir", nullable=false) ), 
        @AttributeOverride(name="idKategorija", column=@Column(name="id_kategorija", nullable=false) ) } )
    public FaziId getId() {
        return this.id;
    }
    
    public void setId(FaziId id) {
        this.id = id;
    }

    
    @Column(name="opis_faza", nullable=false, length=4)
    public String getOpisFaza() {
        return this.opisFaza;
    }
    
    public void setOpisFaza(String opisFaza) {
        this.opisFaza = opisFaza;
    }

    
    @Column(name="broj_faza")
    public Integer getBrojFaza() {
        return this.brojFaza;
    }
    
    public void setBrojFaza(Integer brojFaza) {
        this.brojFaza = brojFaza;
    }




}


