package com.bazi.ttmk.model;
// Generated Jan 29, 2020, 7:04:22 PM by Hibernate Tools 4.3.5.Final


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * FaziId generated by hbm2java
 */
@Embeddable
public class FaziId  implements java.io.Serializable {


     private int redenBroj;
     private int idTurnir;
     private int idKategorija;

    public FaziId() {
    }

    public FaziId(int redenBroj, int idTurnir, int idKategorija) {
       this.redenBroj = redenBroj;
       this.idTurnir = idTurnir;
       this.idKategorija = idKategorija;
    }
   


    @Column(name="reden_broj", nullable=false)
    public int getRedenBroj() {
        return this.redenBroj;
    }
    
    public void setRedenBroj(int redenBroj) {
        this.redenBroj = redenBroj;
    }


    @Column(name="id_turnir", nullable=false)
    public int getIdTurnir() {
        return this.idTurnir;
    }
    
    public void setIdTurnir(int idTurnir) {
        this.idTurnir = idTurnir;
    }


    @Column(name="id_kategorija", nullable=false)
    public int getIdKategorija() {
        return this.idKategorija;
    }
    
    public void setIdKategorija(int idKategorija) {
        this.idKategorija = idKategorija;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof FaziId) ) return false;
		 FaziId castOther = ( FaziId ) other; 
         
		 return (this.getRedenBroj()==castOther.getRedenBroj())
 && (this.getIdTurnir()==castOther.getIdTurnir())
 && (this.getIdKategorija()==castOther.getIdKategorija());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getRedenBroj();
         result = 37 * result + this.getIdTurnir();
         result = 37 * result + this.getIdKategorija();
         return result;
   }   


}


