package com.bazi.ttmk.model;
// Generated Jan 29, 2020, 7:04:22 PM by Hibernate Tools 4.3.5.Final


import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import javax.persistence.*;

/**
 * FaziId generated by hbm2java
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
@Embeddable
public class FaziId implements java.io.Serializable {

    @Column(name = "reden_broj", nullable = false)
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int redenBroj;

    @Column(name = "id_turnir", nullable = false)
    private int idTurnir;

    @Column(name = "id_kategorija", nullable = false)
    private int idKategorija;
}


