package com.bazi.ttmk.model;
// Generated Jan 29, 2020, 7:04:22 PM by Hibernate Tools 4.3.5.Final


import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import javax.persistence.*;

/**
 * Gradovi generated by hbm2java
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
@Entity
@Table(name = "gradovi",
        uniqueConstraints = @UniqueConstraint(columnNames = "ime_grad"),
        schema = "project")
public class Gradovi implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id_grad", unique = true, nullable = false)
    private int idGrad;

    @Column(name = "ime_grad", unique = true, nullable = false, length = 30)
    private String imeGrad;
}


