package com.bazi.ttmk.model;
// Generated Jan 29, 2020, 7:04:22 PM by Hibernate Tools 4.3.5.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Gradovi generated by hbm2java
 */
@Entity
@Table(name="gradovi",
        uniqueConstraints = @UniqueConstraint(columnNames="ime_grad"),
        schema = "project")
public class Gradovi  implements java.io.Serializable {


     private int idGrad;
     private String imeGrad;

    public Gradovi() {
    }

    public Gradovi(int idGrad, String imeGrad) {
       this.idGrad = idGrad;
       this.imeGrad = imeGrad;
    }
   
     @Id 

    
    @Column(name="id_grad", unique=true, nullable=false)
    public int getIdGrad() {
        return this.idGrad;
    }
    
    public void setIdGrad(int idGrad) {
        this.idGrad = idGrad;
    }

    
    @Column(name="ime_grad", unique=true, nullable=false, length=30)
    public String getImeGrad() {
        return this.imeGrad;
    }
    
    public void setImeGrad(String imeGrad) {
        this.imeGrad = imeGrad;
    }




}


