package com.bazi.ttmk.model;
// Generated Jan 29, 2020, 7:04:22 PM by Hibernate Tools 4.3.5.Final


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Igrachi generated by hbm2java
 */
@Entity
@Table(name="igrachi", schema = "project")
public class Igrachi  implements java.io.Serializable {


     private int idLiceIgrach;
     private Date posledenLekarskiPregled;
     private String opisNaReket;
     private Integer idTim;
     private Integer idKategorija;

    public Igrachi() {
    }

	
    public Igrachi(int idLiceIgrach, Date posledenLekarskiPregled, String opisNaReket) {
        this.idLiceIgrach = idLiceIgrach;
        this.posledenLekarskiPregled = posledenLekarskiPregled;
        this.opisNaReket = opisNaReket;
    }
    public Igrachi(int idLiceIgrach, Date posledenLekarskiPregled, String opisNaReket, Integer idTim, Integer idKategorija) {
       this.idLiceIgrach = idLiceIgrach;
       this.posledenLekarskiPregled = posledenLekarskiPregled;
       this.opisNaReket = opisNaReket;
       this.idTim = idTim;
       this.idKategorija = idKategorija;
    }
   
     @Id 

    
    @Column(name="id_lice_igrach", unique=true, nullable=false)
    public int getIdLiceIgrach() {
        return this.idLiceIgrach;
    }
    
    public void setIdLiceIgrach(int idLiceIgrach) {
        this.idLiceIgrach = idLiceIgrach;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="posleden_lekarski_pregled", nullable=false, length=13)
    public Date getPosledenLekarskiPregled() {
        return this.posledenLekarskiPregled;
    }
    
    public void setPosledenLekarskiPregled(Date posledenLekarskiPregled) {
        this.posledenLekarskiPregled = posledenLekarskiPregled;
    }

    
    @Column(name="opis_na_reket", nullable=false, length=100)
    public String getOpisNaReket() {
        return this.opisNaReket;
    }
    
    public void setOpisNaReket(String opisNaReket) {
        this.opisNaReket = opisNaReket;
    }

    
    @Column(name="id_tim")
    public Integer getIdTim() {
        return this.idTim;
    }
    
    public void setIdTim(Integer idTim) {
        this.idTim = idTim;
    }

    
    @Column(name="id_kategorija")
    public Integer getIdKategorija() {
        return this.idKategorija;
    }
    
    public void setIdKategorija(Integer idKategorija) {
        this.idKategorija = idKategorija;
    }




}


