package com.bazi.ttmk.model;
// Generated Jan 29, 2020, 7:04:22 PM by Hibernate Tools 4.3.5.Final


import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.Date;
import javax.persistence.*;

/**
 * Igrachi generated by hbm2java
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
@Entity
@Table(name = "igrachi", schema = "project")
public class Igrachi implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id_lice_igrach", unique = true, nullable = false)
    private int idLiceIgrach;

    @Temporal(TemporalType.DATE)
    @Column(name = "posleden_lekarski_pregled", nullable = false, length = 13)
    private Date posledenLekarskiPregled;

    @Column(name = "opis_na_reket", nullable = false, length = 100)
    private String opisNaReket;

    @Column(name = "id_tim")
    private Integer idTim;

    @Column(name = "id_kategorija")
    private Integer idKategorija;
}


