package com.bazi.ttmk.model;
// Generated Jan 29, 2020, 7:04:22 PM by Hibernate Tools 4.3.5.Final


import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import javax.persistence.*;

/**
 * Kategorii generated by hbm2java
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
@Entity
@Table(name = "kategorii",
        uniqueConstraints = @UniqueConstraint(columnNames = "ime_kategorija"),
        schema = "project")
public class Kategorii implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id_kategorija", unique = true, nullable = false)
    private int idKategorija;

    @Column(name = "ime_kategorija", unique = true, nullable = false, length = 40)
    private String imeKategorija;
}


