package com.bazi.ttmk.model;
// Generated Jan 29, 2020, 7:04:22 PM by Hibernate Tools 4.3.5.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Kategorii generated by hbm2java
 */
@Entity
@Table(name="kategorii",
        uniqueConstraints = @UniqueConstraint(columnNames="ime_kategorija"),
        schema = "project")
public class Kategorii  implements java.io.Serializable {


     private int idKategorija;
     private String imeKategorija;

    public Kategorii() {
    }

    public Kategorii(int idKategorija, String imeKategorija) {
       this.idKategorija = idKategorija;
       this.imeKategorija = imeKategorija;
    }
   
    @Id
    @Column(name="id_kategorija", unique=true, nullable=false)
    public int getIdKategorija() {
        return this.idKategorija;
    }
    
    public void setIdKategorija(int idKategorija) {
        this.idKategorija = idKategorija;
    }

    
    @Column(name="ime_kategorija", unique=true, nullable=false, length=40)
    public String getImeKategorija() {
        return this.imeKategorija;
    }
    
    public void setImeKategorija(String imeKategorija) {
        this.imeKategorija = imeKategorija;
    }




}


