package com.bazi.ttmk.model;
// Generated Jan 29, 2020, 7:04:22 PM by Hibernate Tools 4.3.5.Final


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Ligi generated by hbm2java
 */
@Entity
@Table(
        name="ligi",
        uniqueConstraints = @UniqueConstraint(columnNames={"id_sezona", "ime_liga"}),
        schema = "project"
)
public class Ligi  implements java.io.Serializable {


     private LigiId id;
     private String imeLiga;

    public Ligi() {
    }

    public Ligi(LigiId id, String imeLiga) {
       this.id = id;
       this.imeLiga = imeLiga;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idLiga", column=@Column(name="id_liga", nullable=false) ), 
        @AttributeOverride(name="idSezona", column=@Column(name="id_sezona", nullable=false) ) } )
    public LigiId getId() {
        return this.id;
    }
    
    public void setId(LigiId id) {
        this.id = id;
    }

    
    @Column(name="ime_liga", nullable=false, length=40)
    public String getImeLiga() {
        return this.imeLiga;
    }
    
    public void setImeLiga(String imeLiga) {
        this.imeLiga = imeLiga;
    }




}


