package com.bazi.ttmk.model;
// Generated Jan 29, 2020, 7:04:22 PM by Hibernate Tools 4.3.5.Final


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * LigiId generated by hbm2java
 */
@Embeddable
public class LigiId  implements java.io.Serializable {


     private int idLiga;
     private int idSezona;

    public LigiId() {
    }

    public LigiId(int idLiga, int idSezona) {
       this.idLiga = idLiga;
       this.idSezona = idSezona;
    }
   


    @Column(name="id_liga", nullable=false)
    public int getIdLiga() {
        return this.idLiga;
    }
    
    public void setIdLiga(int idLiga) {
        this.idLiga = idLiga;
    }


    @Column(name="id_sezona", nullable=false)
    public int getIdSezona() {
        return this.idSezona;
    }
    
    public void setIdSezona(int idSezona) {
        this.idSezona = idSezona;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof LigiId) ) return false;
		 LigiId castOther = ( LigiId ) other; 
         
		 return (this.getIdLiga()==castOther.getIdLiga())
 && (this.getIdSezona()==castOther.getIdSezona());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdLiga();
         result = 37 * result + this.getIdSezona();
         return result;
   }   


}


