package com.bazi.ttmk.model;
// Generated Jan 29, 2020, 7:04:22 PM by Hibernate Tools 4.3.5.Final


import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Ligi generated by hbm2java
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
@Entity
@Table(
        name = "ligi",
        uniqueConstraints = @UniqueConstraint(columnNames = {"id_sezona", "ime_liga"}),
        schema = "project"
)
public class Ligi implements java.io.Serializable {

    @EmbeddedId
    @AttributeOverrides({
            @AttributeOverride(name = "idLiga", column = @Column(name = "id_liga", nullable = false)),
            @AttributeOverride(name = "idSezona", column = @Column(name = "id_sezona", nullable = false))
    })
    private LigiId id;

    @Column(name = "ime_liga", nullable = false, length = 40)
    private String imeLiga;
}


