package com.bazi.ttmk.model;
// Generated Jan 29, 2020, 7:04:22 PM by Hibernate Tools 4.3.5.Final


import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import javax.persistence.*;

/**
 * Mechevi generated by hbm2java
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
@Entity
@Table(
        name = "mechevi",
        uniqueConstraints = {@UniqueConstraint(columnNames = {"id_lice_igrach_domakjin", "id_lice_igrach_gostin", "faza_id_turnir", "faza_id_kategorija", "faza_reden_broj"}),
                @UniqueConstraint(columnNames = {"id_lice_igrach_domakjin", "id_lice_igrach_gostin", "id_natprevar"})},
        schema = "project"
)
public class Mechevi implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id_mech", unique = true, nullable = false)
    private int idMech;

    @Column(name = "id_lice_igrach_domakjin", nullable = false)
    private int idLiceIgrachDomakjin;

    @Column(name = "id_lice_igrach_gostin", nullable = false)
    private int idLiceIgrachGostin;

    @Column(name = "lice_id_sudija")
    private Integer liceIdSudija;

    @Column(name = "faza_id_turnir")
    private Integer fazaIdTurnir;

    @Column(name = "faza_id_kategorija")
    private Integer fazaIdKategorija;

    @Column(name = "faza_reden_broj")
    private Integer fazaRedenBroj;

    @Column(name = "id_natprevar")
    private Integer idNatprevar;

    @Column(name = "dobieni_setovi_domakjin")
    private Integer dobieniSetoviDomakjin;

    @Column(name = "dobieni_setovi_gostin")
    private Integer dobieniSetoviGostin;

}


