package com.bazi.ttmk.model;
// Generated Jan 29, 2020, 7:04:22 PM by Hibernate Tools 4.3.5.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Mechevi generated by hbm2java
 */
@Entity
@Table(
        name="mechevi",
        uniqueConstraints = {@UniqueConstraint(columnNames={"id_lice_igrach_domakjin", "id_lice_igrach_gostin", "faza_id_turnir", "faza_id_kategorija", "faza_reden_broj"}),
                @UniqueConstraint(columnNames={"id_lice_igrach_domakjin", "id_lice_igrach_gostin", "id_natprevar"})},
        schema = "project"
)
public class Mechevi  implements java.io.Serializable {


     private int idMech;
     private int idLiceIgrachDomakjin;
     private int idLiceIgrachGostin;
     private Integer liceIdSudija;
     private Integer fazaIdTurnir;
     private Integer fazaIdKategorija;
     private Integer fazaRedenBroj;
     private Integer idNatprevar;
     private Integer dobieniSetoviDomakjin;
     private Integer dobieniSetoviGostin;

    public Mechevi() {
    }

	
    public Mechevi(int idMech, int idLiceIgrachDomakjin, int idLiceIgrachGostin) {
        this.idMech = idMech;
        this.idLiceIgrachDomakjin = idLiceIgrachDomakjin;
        this.idLiceIgrachGostin = idLiceIgrachGostin;
    }
    public Mechevi(int idMech, int idLiceIgrachDomakjin, int idLiceIgrachGostin, Integer liceIdSudija, Integer fazaIdTurnir, Integer fazaIdKategorija, Integer fazaRedenBroj, Integer idNatprevar, Integer dobieniSetoviDomakjin, Integer dobieniSetoviGostin) {
       this.idMech = idMech;
       this.idLiceIgrachDomakjin = idLiceIgrachDomakjin;
       this.idLiceIgrachGostin = idLiceIgrachGostin;
       this.liceIdSudija = liceIdSudija;
       this.fazaIdTurnir = fazaIdTurnir;
       this.fazaIdKategorija = fazaIdKategorija;
       this.fazaRedenBroj = fazaRedenBroj;
       this.idNatprevar = idNatprevar;
       this.dobieniSetoviDomakjin = dobieniSetoviDomakjin;
       this.dobieniSetoviGostin = dobieniSetoviGostin;
    }
   
     @Id 

    
    @Column(name="id_mech", unique=true, nullable=false)
    public int getIdMech() {
        return this.idMech;
    }
    
    public void setIdMech(int idMech) {
        this.idMech = idMech;
    }

    
    @Column(name="id_lice_igrach_domakjin", nullable=false)
    public int getIdLiceIgrachDomakjin() {
        return this.idLiceIgrachDomakjin;
    }
    
    public void setIdLiceIgrachDomakjin(int idLiceIgrachDomakjin) {
        this.idLiceIgrachDomakjin = idLiceIgrachDomakjin;
    }

    
    @Column(name="id_lice_igrach_gostin", nullable=false)
    public int getIdLiceIgrachGostin() {
        return this.idLiceIgrachGostin;
    }
    
    public void setIdLiceIgrachGostin(int idLiceIgrachGostin) {
        this.idLiceIgrachGostin = idLiceIgrachGostin;
    }

    
    @Column(name="lice_id_sudija")
    public Integer getLiceIdSudija() {
        return this.liceIdSudija;
    }
    
    public void setLiceIdSudija(Integer liceIdSudija) {
        this.liceIdSudija = liceIdSudija;
    }

    
    @Column(name="faza_id_turnir")
    public Integer getFazaIdTurnir() {
        return this.fazaIdTurnir;
    }
    
    public void setFazaIdTurnir(Integer fazaIdTurnir) {
        this.fazaIdTurnir = fazaIdTurnir;
    }

    
    @Column(name="faza_id_kategorija")
    public Integer getFazaIdKategorija() {
        return this.fazaIdKategorija;
    }
    
    public void setFazaIdKategorija(Integer fazaIdKategorija) {
        this.fazaIdKategorija = fazaIdKategorija;
    }

    
    @Column(name="faza_reden_broj")
    public Integer getFazaRedenBroj() {
        return this.fazaRedenBroj;
    }
    
    public void setFazaRedenBroj(Integer fazaRedenBroj) {
        this.fazaRedenBroj = fazaRedenBroj;
    }

    
    @Column(name="id_natprevar")
    public Integer getIdNatprevar() {
        return this.idNatprevar;
    }
    
    public void setIdNatprevar(Integer idNatprevar) {
        this.idNatprevar = idNatprevar;
    }

    
    @Column(name="dobieni_setovi_domakjin")
    public Integer getDobieniSetoviDomakjin() {
        return this.dobieniSetoviDomakjin;
    }
    
    public void setDobieniSetoviDomakjin(Integer dobieniSetoviDomakjin) {
        this.dobieniSetoviDomakjin = dobieniSetoviDomakjin;
    }

    
    @Column(name="dobieni_setovi_gostin")
    public Integer getDobieniSetoviGostin() {
        return this.dobieniSetoviGostin;
    }
    
    public void setDobieniSetoviGostin(Integer dobieniSetoviGostin) {
        this.dobieniSetoviGostin = dobieniSetoviGostin;
    }




}


