package com.bazi.ttmk.model;
// Generated Jan 29, 2020, 7:04:22 PM by Hibernate Tools 4.3.5.Final


import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.Date;
import javax.persistence.*;

/**
 * Natprevari generated by hbm2java
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
@Entity
@Table(
        name = "natprevari",
        uniqueConstraints = @UniqueConstraint(columnNames = {"data_odigran", "id_tim_domakjin", "id_tim_gostin"}),
        schema = "project"
)
public class Natprevari implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id_natprevar", unique = true, nullable = false)
    private int idNatprevar;

    @Temporal(TemporalType.DATE)
    @Column(name = "data_odigran", nullable = false, length = 13)
    private Date dataOdigran;

    @Column(name = "id_tim_domakjin", nullable = false)
    private int idTimDomakjin;

    @Column(name = "id_tim_gostin", nullable = false)
    private int idTimGostin;

    @Column(name = "id_sala")
    private Integer idSala;

    @Column(name = "id_liga")
    private Integer idLiga;

    @Column(name = "id_sezona")
    private Integer idSezona;

    @Column(name = "kolo")
    private Integer kolo;

    @Column(name = "dobieni_mechevi_domakjin")
    private Integer dobieniMecheviDomakjin;

    @Column(name = "dobieni_mechevi_gostin")
    private Integer dobieniMecheviGostin;
}


