package com.bazi.ttmk.model;
// Generated Jan 29, 2020, 7:04:22 PM by Hibernate Tools 4.3.5.Final


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Natprevari generated by hbm2java
 */
@Entity
@Table(
        name="natprevari",
        uniqueConstraints = @UniqueConstraint(columnNames={"data_odigran", "id_tim_domakjin", "id_tim_gostin"}),
        schema = "project"
)
public class Natprevari  implements java.io.Serializable {


     private int idNatprevar;
     private Date dataOdigran;
     private int idTimDomakjin;
     private int idTimGostin;
     private Integer idSala;
     private Integer idLiga;
     private Integer idSezona;
     private Integer kolo;
     private Integer dobieniMecheviDomakjin;
     private Integer dobieniMecheviGostin;

    public Natprevari() {
    }

	
    public Natprevari(int idNatprevar, Date dataOdigran, int idTimDomakjin, int idTimGostin) {
        this.idNatprevar = idNatprevar;
        this.dataOdigran = dataOdigran;
        this.idTimDomakjin = idTimDomakjin;
        this.idTimGostin = idTimGostin;
    }
    public Natprevari(int idNatprevar, Date dataOdigran, int idTimDomakjin, int idTimGostin, Integer idSala, Integer idLiga, Integer idSezona, Integer kolo, Integer dobieniMecheviDomakjin, Integer dobieniMecheviGostin) {
       this.idNatprevar = idNatprevar;
       this.dataOdigran = dataOdigran;
       this.idTimDomakjin = idTimDomakjin;
       this.idTimGostin = idTimGostin;
       this.idSala = idSala;
       this.idLiga = idLiga;
       this.idSezona = idSezona;
       this.kolo = kolo;
       this.dobieniMecheviDomakjin = dobieniMecheviDomakjin;
       this.dobieniMecheviGostin = dobieniMecheviGostin;
    }
   
     @Id 

    
    @Column(name="id_natprevar", unique=true, nullable=false)
    public int getIdNatprevar() {
        return this.idNatprevar;
    }
    
    public void setIdNatprevar(int idNatprevar) {
        this.idNatprevar = idNatprevar;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="data_odigran", nullable=false, length=13)
    public Date getDataOdigran() {
        return this.dataOdigran;
    }
    
    public void setDataOdigran(Date dataOdigran) {
        this.dataOdigran = dataOdigran;
    }

    
    @Column(name="id_tim_domakjin", nullable=false)
    public int getIdTimDomakjin() {
        return this.idTimDomakjin;
    }
    
    public void setIdTimDomakjin(int idTimDomakjin) {
        this.idTimDomakjin = idTimDomakjin;
    }

    
    @Column(name="id_tim_gostin", nullable=false)
    public int getIdTimGostin() {
        return this.idTimGostin;
    }
    
    public void setIdTimGostin(int idTimGostin) {
        this.idTimGostin = idTimGostin;
    }

    
    @Column(name="id_sala")
    public Integer getIdSala() {
        return this.idSala;
    }
    
    public void setIdSala(Integer idSala) {
        this.idSala = idSala;
    }

    
    @Column(name="id_liga")
    public Integer getIdLiga() {
        return this.idLiga;
    }
    
    public void setIdLiga(Integer idLiga) {
        this.idLiga = idLiga;
    }

    
    @Column(name="id_sezona")
    public Integer getIdSezona() {
        return this.idSezona;
    }
    
    public void setIdSezona(Integer idSezona) {
        this.idSezona = idSezona;
    }

    
    @Column(name="kolo")
    public Integer getKolo() {
        return this.kolo;
    }
    
    public void setKolo(Integer kolo) {
        this.kolo = kolo;
    }

    
    @Column(name="dobieni_mechevi_domakjin")
    public Integer getDobieniMecheviDomakjin() {
        return this.dobieniMecheviDomakjin;
    }
    
    public void setDobieniMecheviDomakjin(Integer dobieniMecheviDomakjin) {
        this.dobieniMecheviDomakjin = dobieniMecheviDomakjin;
    }

    
    @Column(name="dobieni_mechevi_gostin")
    public Integer getDobieniMecheviGostin() {
        return this.dobieniMecheviGostin;
    }
    
    public void setDobieniMecheviGostin(Integer dobieniMecheviGostin) {
        this.dobieniMecheviGostin = dobieniMecheviGostin;
    }




}


