package com.bazi.ttmk.model;
// Generated Jan 29, 2020, 7:04:22 PM by Hibernate Tools 4.3.5.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * RegistriraniLica generated by hbm2java
 */
@Entity
@Table(
        name="registrirani_lica",
        uniqueConstraints = @UniqueConstraint(columnNames={"ime_lice", "prezime_lice", "godini_lice"}),
        schema = "project"
)
public class RegistriraniLica  implements java.io.Serializable {


     private int idLice;
     private String imeLice;
     private String prezimeLice;
     private int godiniLice;
     private int idGrad;

    public RegistriraniLica() {
    }

    public RegistriraniLica(int idLice, String imeLice, String prezimeLice, int godiniLice, int idGrad) {
       this.idLice = idLice;
       this.imeLice = imeLice;
       this.prezimeLice = prezimeLice;
       this.godiniLice = godiniLice;
       this.idGrad = idGrad;
    }
   
     @Id 

    
    @Column(name="id_lice", unique=true, nullable=false)
    public int getIdLice() {
        return this.idLice;
    }
    
    public void setIdLice(int idLice) {
        this.idLice = idLice;
    }

    
    @Column(name="ime_lice", nullable=false, length=20)
    public String getImeLice() {
        return this.imeLice;
    }
    
    public void setImeLice(String imeLice) {
        this.imeLice = imeLice;
    }

    
    @Column(name="prezime_lice", nullable=false, length=20)
    public String getPrezimeLice() {
        return this.prezimeLice;
    }
    
    public void setPrezimeLice(String prezimeLice) {
        this.prezimeLice = prezimeLice;
    }

    
    @Column(name="godini_lice", nullable=false)
    public int getGodiniLice() {
        return this.godiniLice;
    }
    
    public void setGodiniLice(int godiniLice) {
        this.godiniLice = godiniLice;
    }

    
    @Column(name="id_grad", nullable=false)
    public int getIdGrad() {
        return this.idGrad;
    }
    
    public void setIdGrad(int idGrad) {
        this.idGrad = idGrad;
    }




}


