package com.bazi.ttmk.model;
// Generated Jan 29, 2020, 7:04:22 PM by Hibernate Tools 4.3.5.Final


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SetoviId generated by hbm2java
 */
@Embeddable
public class SetoviId  implements java.io.Serializable {


     private int redenBroj;
     private int idMech;

    public SetoviId() {
    }

    public SetoviId(int redenBroj, int idMech) {
       this.redenBroj = redenBroj;
       this.idMech = idMech;
    }
   


    @Column(name="reden_broj", nullable=false)
    public int getRedenBroj() {
        return this.redenBroj;
    }
    
    public void setRedenBroj(int redenBroj) {
        this.redenBroj = redenBroj;
    }


    @Column(name="id_mech", nullable=false)
    public int getIdMech() {
        return this.idMech;
    }
    
    public void setIdMech(int idMech) {
        this.idMech = idMech;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SetoviId) ) return false;
		 SetoviId castOther = ( SetoviId ) other; 
         
		 return (this.getRedenBroj()==castOther.getRedenBroj())
 && (this.getIdMech()==castOther.getIdMech());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getRedenBroj();
         result = 37 * result + this.getIdMech();
         return result;
   }   


}


