package com.bazi.ttmk.model;
// Generated Jan 29, 2020, 7:04:22 PM by Hibernate Tools 4.3.5.Final


import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Setovi generated by hbm2java
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
@Entity
@Table(name = "setovi", schema = "project")
public class Setovi implements java.io.Serializable {

    @EmbeddedId
    @AttributeOverrides({
            @AttributeOverride(name = "redenBroj", column = @Column(name = "reden_broj", nullable = false)),
            @AttributeOverride(name = "idMech", column = @Column(name = "id_mech", nullable = false))
    })
    private SetoviId id;

    @Column(name = "poeni_gostin", nullable = false)
    private int poeniGostin;

    @Column(name = "poeni_domakjin", nullable = false)
    private int poeniDomakjin;
}


