package com.bazi.ttmk.model;
// Generated Jan 29, 2020, 7:04:22 PM by Hibernate Tools 4.3.5.Final


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Setovi generated by hbm2java
 */
@Entity
@Table(name="setovi", schema = "project")
public class Setovi  implements java.io.Serializable {


     private SetoviId id;
     private int poeniGostin;
     private int poeniDomakjin;

    public Setovi() {
    }

    public Setovi(SetoviId id, int poeniGostin, int poeniDomakjin) {
       this.id = id;
       this.poeniGostin = poeniGostin;
       this.poeniDomakjin = poeniDomakjin;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="redenBroj", column=@Column(name="reden_broj", nullable=false) ), 
        @AttributeOverride(name="idMech", column=@Column(name="id_mech", nullable=false) ) } )
    public SetoviId getId() {
        return this.id;
    }
    
    public void setId(SetoviId id) {
        this.id = id;
    }

    
    @Column(name="poeni_gostin", nullable=false)
    public int getPoeniGostin() {
        return this.poeniGostin;
    }
    
    public void setPoeniGostin(int poeniGostin) {
        this.poeniGostin = poeniGostin;
    }

    
    @Column(name="poeni_domakjin", nullable=false)
    public int getPoeniDomakjin() {
        return this.poeniDomakjin;
    }
    
    public void setPoeniDomakjin(int poeniDomakjin) {
        this.poeniDomakjin = poeniDomakjin;
    }




}


