package com.bazi.ttmk.model;
// Generated Jan 29, 2020, 7:04:22 PM by Hibernate Tools 4.3.5.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Sezoni generated by hbm2java
 */
@Entity
@Table(name="sezoni", schema = "project")
public class Sezoni  implements java.io.Serializable {


     private int idSezona;
     private String pretsedatel;
     private String godina;

    public Sezoni() {
    }

    public Sezoni(int idSezona, String pretsedatel, String godina) {
       this.idSezona = idSezona;
       this.pretsedatel = pretsedatel;
       this.godina = godina;
    }
   
     @Id 

    
    @Column(name="id_sezona", unique=true, nullable=false)
    public int getIdSezona() {
        return this.idSezona;
    }
    
    public void setIdSezona(int idSezona) {
        this.idSezona = idSezona;
    }

    
    @Column(name="pretsedatel", nullable=false, length=30)
    public String getPretsedatel() {
        return this.pretsedatel;
    }
    
    public void setPretsedatel(String pretsedatel) {
        this.pretsedatel = pretsedatel;
    }

    
    @Column(name="godina", nullable=false, length=9)
    public String getGodina() {
        return this.godina;
    }
    
    public void setGodina(String godina) {
        this.godina = godina;
    }




}


