package com.bazi.ttmk.model;
// Generated Jan 29, 2020, 7:04:22 PM by Hibernate Tools 4.3.5.Final


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Spagja generated by hbm2java
 */
@Entity
@Table(name="spagja", schema = "project")
public class Spagja  implements java.io.Serializable {


     private SpagjaId id;
     private int timPoeni;

    public Spagja() {
    }

    public Spagja(SpagjaId id, int timPoeni) {
       this.id = id;
       this.timPoeni = timPoeni;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idLiga", column=@Column(name="id_liga", nullable=false) ), 
        @AttributeOverride(name="idSezona", column=@Column(name="id_sezona", nullable=false) ), 
        @AttributeOverride(name="idTim", column=@Column(name="id_tim", nullable=false) ) } )
    public SpagjaId getId() {
        return this.id;
    }
    
    public void setId(SpagjaId id) {
        this.id = id;
    }

    
    @Column(name="tim_poeni", nullable=false)
    public int getTimPoeni() {
        return this.timPoeni;
    }
    
    public void setTimPoeni(int timPoeni) {
        this.timPoeni = timPoeni;
    }




}


