package com.bazi.ttmk.model;
// Generated Jan 29, 2020, 7:04:22 PM by Hibernate Tools 4.3.5.Final


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SpagjaId generated by hbm2java
 */
@Embeddable
public class SpagjaId  implements java.io.Serializable {


     private int idLiga;
     private int idSezona;
     private int idTim;

    public SpagjaId() {
    }

    public SpagjaId(int idLiga, int idSezona, int idTim) {
       this.idLiga = idLiga;
       this.idSezona = idSezona;
       this.idTim = idTim;
    }
   


    @Column(name="id_liga", nullable=false)
    public int getIdLiga() {
        return this.idLiga;
    }
    
    public void setIdLiga(int idLiga) {
        this.idLiga = idLiga;
    }


    @Column(name="id_sezona", nullable=false)
    public int getIdSezona() {
        return this.idSezona;
    }
    
    public void setIdSezona(int idSezona) {
        this.idSezona = idSezona;
    }


    @Column(name="id_tim", nullable=false)
    public int getIdTim() {
        return this.idTim;
    }
    
    public void setIdTim(int idTim) {
        this.idTim = idTim;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SpagjaId) ) return false;
		 SpagjaId castOther = ( SpagjaId ) other; 
         
		 return (this.getIdLiga()==castOther.getIdLiga())
 && (this.getIdSezona()==castOther.getIdSezona())
 && (this.getIdTim()==castOther.getIdTim());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdLiga();
         result = 37 * result + this.getIdSezona();
         result = 37 * result + this.getIdTim();
         return result;
   }   


}


