package com.bazi.ttmk.model;
// Generated Jan 29, 2020, 7:04:22 PM by Hibernate Tools 4.3.5.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Sudii generated by hbm2java
 */
@Entity
@Table(name="sudii", schema = "project")
public class Sudii  implements java.io.Serializable {


     private int idLiceSudija;
     private String titula;

    public Sudii() {
    }

    public Sudii(int idLiceSudija, String titula) {
       this.idLiceSudija = idLiceSudija;
       this.titula = titula;
    }
   
     @Id 

    
    @Column(name="id_lice_sudija", unique=true, nullable=false)
    public int getIdLiceSudija() {
        return this.idLiceSudija;
    }
    
    public void setIdLiceSudija(int idLiceSudija) {
        this.idLiceSudija = idLiceSudija;
    }

    
    @Column(name="titula", nullable=false, length=30)
    public String getTitula() {
        return this.titula;
    }
    
    public void setTitula(String titula) {
        this.titula = titula;
    }




}


