package com.bazi.ttmk.model;
// Generated Jan 29, 2020, 7:04:22 PM by Hibernate Tools 4.3.5.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Timovi generated by hbm2java
 */
@Entity
@Table(
        name="timovi",
        uniqueConstraints = @UniqueConstraint(columnNames="kontakt_email"),
        schema = "project"
)
public class Timovi  implements java.io.Serializable {


     private int idTim;
     private String imeTim;
     private int godinaOsnovan;
     private String kontaktEmail;
     private String kontaktTelefon;
     private String kontaktLice;
     private int idGrad;

    public Timovi() {
    }

	
    public Timovi(int idTim, String imeTim, int godinaOsnovan, String kontaktEmail, int idGrad) {
        this.idTim = idTim;
        this.imeTim = imeTim;
        this.godinaOsnovan = godinaOsnovan;
        this.kontaktEmail = kontaktEmail;
        this.idGrad = idGrad;
    }
    public Timovi(int idTim, String imeTim, int godinaOsnovan, String kontaktEmail, String kontaktTelefon, String kontaktLice, int idGrad) {
       this.idTim = idTim;
       this.imeTim = imeTim;
       this.godinaOsnovan = godinaOsnovan;
       this.kontaktEmail = kontaktEmail;
       this.kontaktTelefon = kontaktTelefon;
       this.kontaktLice = kontaktLice;
       this.idGrad = idGrad;
    }
   
     @Id 

    
    @Column(name="id_tim", unique=true, nullable=false)
    public int getIdTim() {
        return this.idTim;
    }
    
    public void setIdTim(int idTim) {
        this.idTim = idTim;
    }

    
    @Column(name="ime_tim", nullable=false, length=30)
    public String getImeTim() {
        return this.imeTim;
    }
    
    public void setImeTim(String imeTim) {
        this.imeTim = imeTim;
    }

    
    @Column(name="godina_osnovan", nullable=false)
    public int getGodinaOsnovan() {
        return this.godinaOsnovan;
    }
    
    public void setGodinaOsnovan(int godinaOsnovan) {
        this.godinaOsnovan = godinaOsnovan;
    }

    
    @Column(name="kontakt_email", unique=true, nullable=false, length=50)
    public String getKontaktEmail() {
        return this.kontaktEmail;
    }
    
    public void setKontaktEmail(String kontaktEmail) {
        this.kontaktEmail = kontaktEmail;
    }

    
    @Column(name="kontakt_telefon", length=12)
    public String getKontaktTelefon() {
        return this.kontaktTelefon;
    }
    
    public void setKontaktTelefon(String kontaktTelefon) {
        this.kontaktTelefon = kontaktTelefon;
    }

    
    @Column(name="kontakt_lice", length=30)
    public String getKontaktLice() {
        return this.kontaktLice;
    }
    
    public void setKontaktLice(String kontaktLice) {
        this.kontaktLice = kontaktLice;
    }

    
    @Column(name="id_grad", nullable=false)
    public int getIdGrad() {
        return this.idGrad;
    }
    
    public void setIdGrad(int idGrad) {
        this.idGrad = idGrad;
    }




}


