// Generated Jan 29, 2020, 7:04:22 PM by Hibernate Tools 4.3.5.Final
package com.bazi.ttmk.model;


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TurniriId generated by hbm2java
 */
@Embeddable
public class TurniriId  implements java.io.Serializable {


     private int idTurnir;
     private int idKategorija;

    public TurniriId() {
    }

    public TurniriId(int idTurnir, int idKategorija) {
       this.idTurnir = idTurnir;
       this.idKategorija = idKategorija;
    }
   


    @Column(name="id_turnir", nullable=false)
    public int getIdTurnir() {
        return this.idTurnir;
    }
    
    public void setIdTurnir(int idTurnir) {
        this.idTurnir = idTurnir;
    }


    @Column(name="id_kategorija", nullable=false)
    public int getIdKategorija() {
        return this.idKategorija;
    }
    
    public void setIdKategorija(int idKategorija) {
        this.idKategorija = idKategorija;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TurniriId) ) return false;
		 TurniriId castOther = ( TurniriId ) other; 
         
		 return (this.getIdTurnir()==castOther.getIdTurnir())
 && (this.getIdKategorija()==castOther.getIdKategorija());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdTurnir();
         result = 37 * result + this.getIdKategorija();
         return result;
   }   


}


