package com.bazi.ttmk.model;
// Generated Jan 29, 2020, 7:04:22 PM by Hibernate Tools 4.3.5.Final


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Turniri generated by hbm2java
 */
@Entity
@Table(
        name="turniri",
        uniqueConstraints = @UniqueConstraint(columnNames={"ime_turnir", "id_sezona", "data_na_odrzhuvanje", "id_kategorija"}),
        schema = "project"
)
public class Turniri  implements java.io.Serializable {


     private TurniriId id;
     private String imeTurnir;
     private Date dataNaOdrzhuvanje;
     private int participacija;
     private int idGrad;
     private int idSezona;

    public Turniri() {
    }

    public Turniri(TurniriId id, String imeTurnir, Date dataNaOdrzhuvanje, int participacija, int idGrad, int idSezona) {
       this.id = id;
       this.imeTurnir = imeTurnir;
       this.dataNaOdrzhuvanje = dataNaOdrzhuvanje;
       this.participacija = participacija;
       this.idGrad = idGrad;
       this.idSezona = idSezona;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idTurnir", column=@Column(name="id_turnir", nullable=false) ), 
        @AttributeOverride(name="idKategorija", column=@Column(name="id_kategorija", nullable=false) ) } )
    public TurniriId getId() {
        return this.id;
    }
    
    public void setId(TurniriId id) {
        this.id = id;
    }

    
    @Column(name="ime_turnir", nullable=false, length=50)
    public String getImeTurnir() {
        return this.imeTurnir;
    }
    
    public void setImeTurnir(String imeTurnir) {
        this.imeTurnir = imeTurnir;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="data_na_odrzhuvanje", nullable=false, length=13)
    public Date getDataNaOdrzhuvanje() {
        return this.dataNaOdrzhuvanje;
    }
    
    public void setDataNaOdrzhuvanje(Date dataNaOdrzhuvanje) {
        this.dataNaOdrzhuvanje = dataNaOdrzhuvanje;
    }

    
    @Column(name="participacija", nullable=false)
    public int getParticipacija() {
        return this.participacija;
    }
    
    public void setParticipacija(int participacija) {
        this.participacija = participacija;
    }

    
    @Column(name="id_grad", nullable=false)
    public int getIdGrad() {
        return this.idGrad;
    }
    
    public void setIdGrad(int idGrad) {
        this.idGrad = idGrad;
    }

    
    @Column(name="id_sezona", nullable=false)
    public int getIdSezona() {
        return this.idSezona;
    }
    
    public void setIdSezona(int idSezona) {
        this.idSezona = idSezona;
    }




}


