insert into Kategorii(ime_kategorija) values('Сениори')
insert into Kategorii(ime_kategorija) values('Сениорки')
insert into Kategorii(ime_kategorija) values('Сениори У-21')
insert into Kategorii(ime_kategorija) values('Сениорки У-21')
insert into Kategorii(ime_kategorija) values('Јуниори У-18')
insert into Kategorii(ime_kategorija) values('Јуниорки У-18')
insert into Kategorii(ime_kategorija) values('Кадети У-15')
insert into Kategorii(ime_kategorija) values('Кадетки У-15')
insert into Kategorii(ime_kategorija) values('Млади кадети У-12')
insert into Kategorii(ime_kategorija) values('Млади кадетки У-12')

insert into Sezoni(pretsedatel, godina) values('Венко Стојанов','2017/2018')
insert into Sezoni(pretsedatel, godina) values('Јасмина Стоименова','2018/2019')
insert into Sezoni(pretsedatel, godina) values('Дејан Сламков','2019/2020')

insert into gradovi(ime_grad) values('Скопје')
insert into gradovi(ime_grad) values('Радовиш')
insert into gradovi(ime_grad) values('Гевгелија')
insert into gradovi(ime_grad) values('Виница')
insert into gradovi(ime_grad) values('Валандово')
insert into gradovi(ime_grad) values('Струмица')
insert into gradovi(ime_grad) values('Прилеп')
insert into gradovi(ime_grad) values('Штип')
insert into gradovi(ime_grad) values('Кочани')
insert into gradovi(ime_grad) values('Битола')
insert into gradovi(ime_grad) values('Струга')
insert into gradovi(ime_grad) values('Охрид')
insert into gradovi(ime_grad) values('Крушево')
insert into gradovi(ime_grad) values('Велес')
insert into gradovi(ime_grad) values('Крива Паланка')
insert into gradovi(ime_grad) values('Кратово')
insert into gradovi(ime_grad) values('Кавадарци')
insert into gradovi(ime_grad) values('Македонска Каменица')
insert into gradovi(ime_grad) values('Куманово')

insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Аврам','Крстев',35,1)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Евтим','Илиев',27,1)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Бранко','Тодоров',29,1)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Герасим','Манев',42,1)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Антониј','Спасов',47,1)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Војкан','Евтимов',26,1)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Ѓоко','Левески',39,1)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Делјан','Сотиров',36,1)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Живко','Поповски',28,1)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Игнатиј','Јанев',44,1)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Михаил','Божинов',37,1)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Сребре','Ангелов',26,1)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Теодор','Теодосиев',62,1)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Цветан','Петкоски',54,1)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Климент','Лазарев',68,1)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Љупчо','Стевков',22,1)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Никита','Сеизов',50,1)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Здравко','Илиев',55,1)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Стојан','Милошевски',46,1)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Симон','Гавазов',48,1)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Нестор','Лозановски',69,1)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Крсте','Петрески',50,1)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Игнат','Јовановски',24,1)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Прокопиј','Николовски',56,1)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Алимпиј','Петковиќ',59,1)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Лука','Видоевски',52,1)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Данаил','Богданоски',29,1)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Лазар','Димоски',43,2)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Тодор','Петковиќ',49,2)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Благој','Огненоски',43,2)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Митре','Васевски',53,2)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Чедомир','Арсов',54,2)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Часлав','Трајкоски',23,2)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Богослав','Јаневски',43,2)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Здравко','Тасевски',67,3)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Лазар','Туџаровски',39,3)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Јордан','Милков',68,3)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Цветан','Петковиќ',29,3)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Глигор','Петковиќ',31,3)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Костадин','Стојановски',48,3)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Рајко','Трајкоски',53,3)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Борис','Мартиноски',34,3)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Апостол','Арсов',22,3)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Партениј','Јовановски',40,4)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Душко','Андревски',34,4)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Никола','Дуридански',53,4)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Живко','Атанасов',52,4)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Златко','Стаменков',21,4)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Чедомир','Пандевски',55,4)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Давид','Петровски',63,5)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Теофан','Арсов',58,5)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Никита','Барабановски',47,5)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Оливер','Јанчески',66,5)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Веселин','Станковски',25,5)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Димитар','Димоски',67,5)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Велјан','Бајрактаров',28,6)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Димитар','Матракоски',22,6)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Силјан','Јованоски',35,6)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Велјан','Огненоски',57,6)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Гроздан','Брашнарски',35,6)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Александар','Ѓаконовски',63,6)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Ѓорѓи','Јовановски',38,7)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Јаков','Арсов',67,7)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Илија','Петрески',23,7)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Михаил','Грковски',57,7)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Еразмо','Томовски',35,7)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Теофил','Бошев',32,8)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Велјан','Мартиноски',65,8)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Прокопиј','Тасевски',37,8)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Златан','Крстевски',69,8)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Теофил','Наумоски',46,9)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Славе','Алексоски',29,9)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Григор','Талевски',27,9)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Симон','Рустемовски',65,9)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Огнен','Николовски',35,9)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Павле','Борозанов',57,10)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Јаков','Арсов',37,10)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Богатин','Јовановски',60,10)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Бојан','Крстевски',38,10)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Љупчо','Ристов',51,10)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Аритон','Јовановски',31,11)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Веселин','Станковски',24,11)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Игнатиј','Атанасов',40,11)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Никифор','Темелков',66,11)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Христо','Петрески',45,11)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Ристе','Ѓаконовски',47,11)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Веселин','Драгомиров',50,12)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Кузман','Илиев',51,12)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Пантелејмон','Поповски',55,12)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Лука','Поповски',61,12)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Славе','Стојановски',25,12)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Темелко','Огненоски',28,12)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Христо','Апостолоски',34,12)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Спасе','Ацевски',59,12)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Митре','Видоевски',21,12)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Теодор','Станковски',62,12)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Веселин','Бошев',32,12)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Атанас','Видоевски',61,13)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Македон','Наумоски',38,13)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Рајко','Стојанов',23,13)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Софрониј','Барабановски',41,13)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Јосиф','Апостолоски',48,13)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Ромил','Лазарев',59,14)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Марин','Јованоски',22,14)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Глигор','Грковски',60,14)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Силјан','Брашнарски',61,14)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Sвонко','Рангелов',25,14)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Доротеј','Апостолоски',30,14)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Евгениј','Стаменков',28,15)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Владимир','Поповски',69,15)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Григор','Тасевски',56,15)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Гоце','Стаменков',39,15)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Митре','Огненоски',53,15)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Христо','Илиев',32,16)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Владимир','Томовски',57,16)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Димитриј','Јовановски',31,16)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Аритон','Стаменков',25,17)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Оливер','Додевски',65,17)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Андреј','Јаневски',31,18)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Славе','Барабановски',40,18)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Методиј','Владиковски',21,19)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Љупчо','Стојанов',29,19)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Гроздан','Брашнарски',42,19)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Ромил','Станојковски',42,19)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Ѓорче','Јованоски',51,19)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Илија','Наумоски',13,1)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Виктор','Баџаков',10,1)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Ѓоко','Бајрактаров',13,1)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Данаил','Јовановски',20,1)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Леонид','Крстевски',17,1)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Богдан','Темелков',16,1)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Теодор','Пандевски',5,1)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Цветан','Лозановски',5,1)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Никита','Сеизов',14,1)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Ристе','Гавазов',19,1)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Тодор','Милошевски',20,1)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Делчо','Станојковски',7,1)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Еразмо','Дуридански',8,1)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Антониј','Пецов',17,1)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Гроздан','Арсов',14,1)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Марко','Матракоски',18,1)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Антониј','Баџаков',16,1)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Делјан','Илиев',14,1)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Златан','Веселиновски',16,1)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Златко','Ацевски',13,2)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Дејан','Крстевски',8,2)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Пимен','Петковиќ',20,2)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Панче','Станковски',15,2)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Sвонко','Арсов',14,2)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Козма','Петрески',19,3)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Сребре','Димоски',17,3)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Јане','Лозановски',19,3)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Зафир','Васевски',6,3)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Неделко','Бошев',11,4)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Ѓоко','Станковски',11,4)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Тихомир','Јовановски',14,4)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Филип','Стојановски',20,4)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Љубомир','Димоски',7,4)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Козма','Тодоровски',12,4)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Филип','Јовановски',10,5)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Никола','Крстевски',17,5)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Часлав','Арсов',6,5)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Душко','Рустемовски',9,5)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Христо','Ѓаконовски',10,6)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Арсениј','Стаменков',8,6)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Исак','Стојанов',17,6)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Јане','Матевски',10,6)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Венко','Јовановски',11,6)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Божин','Лозановски',5,6)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Златан','Станковски',14,7)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Неделко','Матевски',18,7)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Атанасиј','Видоевски',6,7)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Рајко','Танески',16,7)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Пимен','Петрески',20,7)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Марин','Додевски',12,7)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Марјан','Матевски',14,7)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Љубен','Тодоровски',5,8)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Исак','Киров',17,8)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Гаврил','Крстевски',17,8)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Василиј','Трајковски',20,8)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Костадин','Танески',17,8)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Петар','Веселиновски',15,8)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Ѓорѓи','Мартиноски',14,8)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Рајко','Милошевски',17,9)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Јаков','Бошев',18,9)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Часлав','Драгомиров',5,9)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Спасе','Трајкоски',18,10)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Козма','Дуридански',8,10)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Гоце','Станковски',16,10)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Трифун','Николовски',12,10)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Никола','Наумоски',4,11)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Чедомир','Сеизов',13,11)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Захариј','Поповски',7,11)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Ангел','Стојановски',16,12)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Андреј','Огненоски',12,12)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Георгиј','Сарафилоски',14,12)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Филип','Станковски',12,12)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Петко','Бајрактаров',6,13)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Ефтим','Пецов',8,13)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Јаков','Јаневски',9,13)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Стефан','Јоноски',20,13)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Јордан','Пандевски',6,13)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Филип','Станојковски',13,13)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Петко','Спасеноски',15,13)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Софрониј','Здравески',18,13)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Ристе','Јаневски',14,13)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Антониј','Николовски',12,13)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Дамјан','Поповски',10,14)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Димитар','Атанасов',10,14)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Чедомир','Стојановски',20,14)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Борјан','Јанчески',8,14)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Димитар','Тодоровски',20,15)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Часлав','Наумоски',19,15)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Антониј','Рустемовски',13,15)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Иринеј','Лозановски',13,15)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Исак','Атанасов',4,15)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Јордан','Трајковски',20,16)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Наум','Станојковски',16,16)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Нестор','Јанчески',19,17)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Антониј','Милошевски',17,17)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Веселин','Дуридански',6,17)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Македон','Драгомиров',18,17)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Емил','Борозанов',10,17)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Методиј','Бошев',19,18)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Чедомир','Јовановски',17,18
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Борис','Темелков',12,18)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Данаил','Петковиќ',14,19)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Иринеј','Лазарев',10,19)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Гроздан','Ацевски',6,19)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Козма','Васевски',4,19)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Методиј','Талевски',10,19)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Теофан','Милошевски',10,19)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Дојчин','Владиковски',5,19)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Дејан','Гавазов',15,19)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Доротеј','Трајковски',14,19)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Рахилка','Николовска',11,1)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Евдокија','Костоска',12,1)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Писана','Баџакова',28,1)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Здравка','Стојанова',15,1)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Зафирка','Јанческа',45,1)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Зорка','Матевска',26,1)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Ана','Танеска',25,1)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Василка','Гавазова',18,1)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Јагода','Станојковска',35,1)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Дамјана','Томовска',30,1)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Војданка','Матевска',18,2)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Милица','Станковска',21,2)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Борка','Милошевска',14,2)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Цвета','Драгомирова',24,2)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Бранка','Ристова',26,2)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Сандра','Димоска',38,3)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Јовка','Јанческа',39,3)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Спасена','Стојановска',30,3)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Гордана','Алексоска',30,3)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Фросина','Сеизова',44,4)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Сава','Пецова',7,4)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Душанка','Ристова',31,4)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Рахела','Спасеноска',17,4)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Сава','Матракоска',32,5)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Домника','Станковска',18,5)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Милица','Рустемовска',17,5)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Голубинка','Тасевска',16,5)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Јана','Томовска',41,6)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Sвезда','Стојанова',33,6)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Дивна','Лазарева',20,6)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Вероника','Рустемовска',10,6)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Стојмена','Туџаровска',11,6)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Славенка','Тасевска',21,7)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Божана','Трајкоска',8,7)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Сара','Ѓаконовска',41,7)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Неда','Јовановска',43,7)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Елисавета','Наумоска',36,8)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Неда','Кирова',9,8)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Марина','Јовановска',20,8)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Анѓа','Драгомирова',28,8)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Живка','Алексоска',32,9)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Светлана','Јаневска',10,9)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Рајна','Наумоска',11,9)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Цвета','Петреска',23,9)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Јана','Јованоскиа',15,10)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Зора','Јованоскиа',51,10)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Марта','Здравеска',21,10)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Николина','Стојанова',14,10)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Параскева','Борозанова',48,11)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Грозда','Јаневска',17,11)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Борјана','Нешкоска',17,11)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Ана','Спасеноска',15,11)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Зорица','Поповска',14,12)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Загорка','Брашнарска',13,12)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Трајанка','Темелкова',11,12)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Никодина','Здравеска',9,12)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Искра','Кирова',17,13)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Голубинка','Стојановска',36,13)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Искра','Јанческа',37,13)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Николина','Темелкова',12,13)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Кита','Бајрактарова',27,14)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Екатерина','Додевска',26,14)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Рахела','Стојановска',16,14)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Татјана','Станковска',16,14)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Наумка','Илиева',15,15)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Грозда','Апостолоска',15,15)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Цвета','Ристова',17,15)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Горјана','Атанасова',14,15)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Благица','Николовска',13,15)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Сребра','Барабановска',30,16)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Александра','Танеска',43,16)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Серафима','Стојановска',44,16)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Александра','Апостолоска',11,16)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Трајанка','Видоевска',51,16)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Марта','Темелкова',9,17)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Дивна','Крстевска',17,17)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Благуна','Наумоска',8,17)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Блаженка','Поповска',9,17)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Даница','Сеизова',8,17)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Зорица','Стаменкова',9,17)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Филимена','Костоска',12,17)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Ефимија','Трајкоска',32,18)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Јовка','Поповска',44,18)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Петранка','Јованоскиа',14,18)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Марика','Стојановска',15,18)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Катерина','Алексоска',25,18)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Виолета','Томовска',26,18)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Стефанка','Јовановска',13,18)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Драгана','Видоевска',17,18)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Меланија','Рикалоска',17,18)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Ивана','Петковиќ',17,19)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Трена','Трајковска',25,19)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Флоринка','Јовановска',28,19)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Теодора','Станковска',33,19)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Злата','Нешкоска',53,19)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Нада','Бакалова',15,19)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Зорица','Бајрактарова',16,19)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Иванка','Трајкоска',12,19)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Трена','Владиковска',12,19)
insert into Registrirani_Lica (ime_lice,prezime_lice,godini_lice,id_grad) values('Кита','Танеска',14,19)

insert into Sudii(id_lice_sudija,titula) values(10,'IU-BB')
insert into Sudii(id_lice_sudija,titula) values(11,'IU-BB')
insert into Sudii(id_lice_sudija,titula) values(76,'IU-BB')
insert into Sudii(id_lice_sudija,titula) values(39,'IU-WB')
insert into Sudii(id_lice_sudija,titula) values(2,'IU-WB')
insert into Sudii(id_lice_sudija,titula) values(271,'NU')
insert into Sudii(id_lice_sudija,titula) values(287,'IU-WB')
insert into Sudii(id_lice_sudija,titula) values(115,'IU-WB')
insert into Sudii(id_lice_sudija,titula) values(128,'NU')
insert into Sudii(id_lice_sudija,titula) values(6,'NU')
insert into Sudii(id_lice_sudija,titula) values(87,'NU')
insert into Sudii(id_lice_sudija,titula) values(258,'NU')
insert into Sudii(id_lice_sudija,titula) values(45,'NU')
insert into Sudii(id_lice_sudija,titula) values(114,'NU')
insert into Sudii(id_lice_sudija,titula) values(346,'NU')


insert into Sali(ime_sala,id_grad) values('Спортска сала „Шабан Трстена“ Чаир',1)
insert into Sali(ime_sala,id_grad) values('Спортска сала „Кале“',1)
insert into Sali(ime_sala,id_grad) values('Спортска сала „А1 арена“',1)
insert into Sali(ime_sala,id_grad) values('Спортска сала „Градски парк“',1)
insert into Sali(ime_sala,id_grad) values('Спортска сала „Расадник“',1)
insert into Sali(ime_sala,id_grad) values('Спортска сала „СРЦ 25-ти мај“',2)
insert into Sali(ime_sala,id_grad) values('Спортска сала „Карев“',3)
insert into Sali(ime_sala,id_grad) values('Спортска сала „Капетан Кирчо Димитриов“',4)
insert into Sali(ime_sala,id_grad) values('Спортска сала „СРЦ Никола Карев“',5)
insert into Sali(ime_sala,id_grad) values('Спортска сала „Парк“',6)
insert into Sali(ime_sala,id_grad) values('Спортска сала „Маркови кули“',7)
insert into Sali(ime_sala,id_grad) values('Спортска сала „Суитлак“',8)
insert into Sali(ime_sala,id_grad) values('Спортска сала „Градски базен-Куманово“',19)

insert into Turniri(ime_turnir,data_na_odrzhuvanje,participacija,id_sala,id_sezona) values('Св. Климент Охридски',now() - interval '1 year 4 days',300,12,2)
insert into Turniri(ime_turnir,data_na_odrzhuvanje,participacija,id_sala,id_sezona) values('Вип турнир - Скопје',now() - interval '8 months',499,1,3)
insert into Turniri(ime_turnir,data_na_odrzhuvanje,participacija,id_sala,id_sezona) values('Телеком мастерс - Скопје',now() - interval '6 year 4 days',600,1,3)

insert into Fazi(id_turnir,opis_faza) values(1,'1')
insert into Fazi(id_turnir,opis_faza) values(1,'1/2')
insert into Fazi(id_turnir,opis_faza) values(2,'1')
insert into Fazi(id_turnir,opis_faza) values(2,'1/2')
insert into Fazi(id_turnir,opis_faza) values(3,'1')
insert into Fazi(id_turnir,opis_faza) values(3,'1/2')

insert into Ligi(id_sezona,ime_liga) values(3,'Супер лига - Машки')
insert into Ligi(id_sezona,ime_liga) values(3,'Прва лига - Машки')
insert into Ligi(id_sezona,ime_liga) values(3,'Втора лига - Машки')
insert into Ligi(id_sezona,ime_liga) values(3,'Супер лига - Женски')

insert into Timovi(ime_tim,godina_osnovan,kontakt_email,kontakt_telefon,kontakt_lice,id_grad) values('Работнички',1960,'ppk.rabotnichki@live.com','','Дарко',1)
insert into Timovi(ime_tim,godina_osnovan,kontakt_email,kontakt_telefon,kontakt_lice,id_grad) values('Влае',2010,'ppk.vlae@hotmail.com','','Митко',1)
insert into Timovi(ime_tim,godina_osnovan,kontakt_email,kontakt_telefon,kontakt_lice,id_grad) values('Спин',2016,'ppk.spin-skopje@hotmail.com','','Влатко',1)
insert into Timovi(ime_tim,godina_osnovan,kontakt_email,kontakt_telefon,kontakt_lice,id_grad) values('Дебар Маало',1999,'debarmaalo.pingpong@live.com','','Хритијан',1)
insert into Timovi(ime_tim,godina_osnovan,kontakt_email,kontakt_telefon,kontakt_lice,id_grad) values('Млади таленти',2015,'ppk.mt@hotmail.com','','Стефан',1)
insert into Timovi(ime_tim,godina_osnovan,kontakt_email,kontakt_telefon,kontakt_lice,id_grad) values('Радовиш', 1980, 'ppk.radovish@hotmail.com','+38977111111','Милче', 2)
insert into Timovi(ime_tim,godina_osnovan,kontakt_email,kontakt_telefon,kontakt_lice,id_grad) values('Гевгелија',1998,'ppk.gevgelija@hotmail.com','','',3)
insert into Timovi(ime_tim,godina_osnovan,kontakt_email,kontakt_telefon,kontakt_lice,id_grad) values('Вин-спин',2008,'ppk.vinspin@hotmail.com','','',4)
insert into Timovi(ime_tim,godina_osnovan,kontakt_email,kontakt_telefon,kontakt_lice,id_grad) values('Вал-топ',2016,'valtop@hotmail.com','','',5)
insert into Timovi(ime_tim,godina_osnovan,kontakt_email,kontakt_telefon,kontakt_lice,id_grad) values('Струмица',1970,'ppk.strumica@hotmail.com','','',6)
insert into Timovi(ime_tim,godina_osnovan,kontakt_email,kontakt_telefon,kontakt_lice,id_grad) values('Маркови кули',1981,'ppk.markovikuli@hotmail.com','','',7)
insert into Timovi(ime_tim,godina_osnovan,kontakt_email,kontakt_telefon,kontakt_lice,id_grad) values('Штип',1975,'ppk.shtip@hotmail.com','','',8)
insert into Timovi(ime_tim,godina_osnovan,kontakt_email,kontakt_telefon,kontakt_lice,id_grad) values('Кочани', 1999, 'ppk.kochani@live.com','+38977222222','Кристијан',9)
insert into Timovi(ime_tim,godina_osnovan,kontakt_email,kontakt_telefon,kontakt_lice,id_grad) values('Мултитекст',2004,'multitekstppk@live.com','','',10)
insert into Timovi(ime_tim,godina_osnovan,kontakt_email,kontakt_telefon,kontakt_lice,id_grad) values('Дрим',1996,'ppk.drimstruga@hotmail.com','','',11)
insert into Timovi(ime_tim,godina_osnovan,kontakt_email,kontakt_telefon,kontakt_lice,id_grad) values('Билјанини Извори',1992,'ppk.ohrid@hotmail.com','','',12)
insert into Timovi(ime_tim,godina_osnovan,kontakt_email,kontakt_telefon,kontakt_lice,id_grad) values('Мечкин Камен',1984,'krushevopingpong@hotmail.com','','',13)
insert into Timovi(ime_tim,godina_osnovan,kontakt_email,kontakt_telefon,kontakt_lice,id_grad) values('Младост',1980,'veles.ppk@hotmail.com','','',14)
insert into Timovi(ime_tim,godina_osnovan,kontakt_email,kontakt_telefon,kontakt_lice,id_grad) values('Паланка',1992,'ppk_kp@hotmail.com','','',15)
insert into Timovi(ime_tim,godina_osnovan,kontakt_email,kontakt_telefon,kontakt_lice,id_grad) values('Радин-спин',2017,'kratovo.ppk@live.com','','',16)
insert into Timovi(ime_tim,godina_osnovan,kontakt_email,kontakt_telefon,kontakt_lice,id_grad) values('Тиквеш',1999,'tikvesh.ppk@hotmail.com','','',17)
insert into Timovi(ime_tim,godina_osnovan,kontakt_email,kontakt_telefon,kontakt_lice,id_grad) values('Каменица',2002,'mak_kamenica_ppk@hotmail.com','','',18)
insert into Timovi(ime_tim,godina_osnovan,kontakt_email,kontakt_telefon,kontakt_lice,id_grad) values('Куманово',1994,'ppkumanovo@hotmail.com','','',19)

insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (1, now() - interval '0 year 10 months','Yasaka',1)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (3, now() - interval '0 year 2 months','Nittaku',1)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (4, now() - interval '0 year 6 months','DHS',1)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (5, now() - interval '1 year 6 months','Butterfly',2)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (7, now() - interval '1 year 9 months','Yinhei',2)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (8, now() - interval '0 year 10 months','Killerspin',2)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (9, now() - interval '1 year 7 months','Joola',2)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (12, now() - interval '1 year 8 months','Joola',3)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (13, now() - interval '1 year 4 months','Andro',3)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (14, now() - interval '0 year 7 months','Tibhar',3)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (15, now() - interval '0 year 7 months','Yasaka',3)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (16, now() - interval '0 year 6 months','Friendship',4)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (17, now() - interval '1 year 6 months','Andro',4)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (18, now() - interval '1 year 0 months','Butterfly',4)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (19, now() - interval '1 year 2 months','Joola',4)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (20, now() - interval '0 year 2 months','DMI',4)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (21, now() - interval '1 year 4 months','Friendship',4)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (22, now() - interval '0 year 2 months','Joola',5)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (23, now() - interval '0 year 10 months','Nittaku',5)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (24, now() - interval '0 year 4 months','Nittaku',5)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (25, now() - interval '1 year 11 months','Joola',5)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (26, now() - interval '0 year 0 months','Yasaka',5)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (27, now() - interval '0 year 2 months','Joola',5)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (28, now() - interval '0 year 3 months','Andro',6)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (29, now() - interval '0 year 11 months','Andro',6)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (30, now() - interval '1 year 5 months','Joola',6)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (31, now() - interval '1 year 8 months','Yinhei',6)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (32, now() - interval '0 year 11 months','Tibhar',6)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (33, now() - interval '0 year 8 months','Butterfly',6)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (34, now() - interval '1 year 1 months','Andro',6)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (35, now() - interval '0 year 8 months','Butterfly',7)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (36, now() - interval '0 year 1 months','Nittaku',7)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (37, now() - interval '1 year 10 months','Andro',7)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (38, now() - interval '0 year 8 months','Friendship',7)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (40, now() - interval '1 year 10 months','Yasaka',7)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (41, now() - interval '1 year 0 months','Yasaka',7)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (42, now() - interval '1 year 10 months','Yinhei',7)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (43, now() - interval '1 year 10 months','729',7)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (44, now() - interval '0 year 0 months','Yasaka',8)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (46, now() - interval '0 year 8 months','Andro',8)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (47, now() - interval '1 year 0 months','Stiga',8)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (48, now() - interval '1 year 0 months','Andro',8)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (49, now() - interval '1 year 2 months','DHS',8)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (50, now() - interval '0 year 6 months','Donic',9)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (51, now() - interval '1 year 3 months','DHS',9)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (52, now() - interval '1 year 8 months','Andro',9)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (53, now() - interval '1 year 1 months','Stiga',9)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (54, now() - interval '1 year 1 months','Joola',9)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (55, now() - interval '1 year 6 months','Joola',9)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (56, now() - interval '0 year 11 months','Andro',10)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (57, now() - interval '1 year 10 months','Andro',10)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (58, now() - interval '0 year 0 months','Stiga',10)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (60, now() - interval '1 year 5 months','Stiga',10)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (61, now() - interval '1 year 5 months','Joola',10)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (62, now() - interval '1 year 8 months','729',10)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (63, now() - interval '0 year 1 months','Andro',11)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (64, now() - interval '1 year 8 months','Butterfly',11)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (65, now() - interval '1 year 11 months','Donic',11)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (66, now() - interval '0 year 3 months','729',11)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (67, now() - interval '1 year 3 months','Killerspin',11)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (68, now() - interval '0 year 1 months','Joola',12)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (69, now() - interval '0 year 5 months','Friendship',12)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (70, now() - interval '0 year 9 months','Nittaku',12)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (71, now() - interval '0 year 5 months','DHS',12)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (77, now() - interval '1 year 7 months','729',13)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (78, now() - interval '0 year 7 months','DHS',13)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (79, now() - interval '0 year 10 months','Yinhei',13)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (80, now() - interval '1 year 5 months','Andro',13)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (81, now() - interval '0 year 0 months','Yasaka',14)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (82, now() - interval '0 year 0 months','Yinhei',14)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (83, now() - interval '1 year 3 months','Butterfly',14)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (84, now() - interval '0 year 4 months','729',14)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (85, now() - interval '1 year 8 months','Donic',14)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (86, now() - interval '1 year 6 months','Friendship',15)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (88, now() - interval '0 year 7 months','Tibhar',15)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (89, now() - interval '1 year 0 months','Sportcraft',15)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (90, now() - interval '0 year 4 months','Yinhei',15)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (91, now() - interval '1 year 5 months','DHS',15)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (92, now() - interval '0 year 11 months','DMI',16)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (93, now() - interval '0 year 1 months','729',16)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (94, now() - interval '0 year 2 months','Stiga',16)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (95, now() - interval '1 year 4 months','Butterfly',16)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (96, now() - interval '1 year 4 months','729',16)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (97, now() - interval '0 year 9 months','Joola',16)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (98, now() - interval '0 year 2 months','Friendship',16)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (100, now() - interval '0 year 3 months','Joola',16)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (101, now() - interval '1 year 8 months','Yasaka',16)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (102, now() - interval '1 year 6 months','Nittaku',16)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (103, now() - interval '1 year 6 months','Butterfly',16)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (104, now() - interval '1 year 11 months','Yinhei',17)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (105, now() - interval '0 year 2 months','DHS',17)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (106, now() - interval '1 year 10 months','Joola',17)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (107, now() - interval '0 year 0 months','729',17)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (108, now() - interval '0 year 8 months','DMI',17)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (109, now() - interval '0 year 3 months','729',18)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (110, now() - interval '1 year 2 months','Yasaka',18)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (111, now() - interval '1 year 6 months','Joola',18)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (112, now() - interval '0 year 11 months','Yasaka',18)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (113, now() - interval '0 year 6 months','Stiga',18)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (116, now() - interval '1 year 6 months','Nittaku',19)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (117, now() - interval '0 year 3 months','Stiga',19)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (118, now() - interval '1 year 9 months','Friendship',19)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (119, now() - interval '0 year 10 months','Sportcraft',19)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (120, now() - interval '0 year 5 months','Andro',20)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (121, now() - interval '0 year 4 months','Tibhar',20)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (122, now() - interval '1 year 7 months','Nittaku',20)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (123, now() - interval '1 year 11 months','Butterfly',21)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (124, now() - interval '0 year 0 months','Andro',21)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (125, now() - interval '0 year 8 months','Yinhei',22)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (126, now() - interval '1 year 5 months','729',22)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (127, now() - interval '1 year 0 months','Joola',23)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (129, now() - interval '0 year 8 months','Andro',23)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (130, now() - interval '0 year 10 months','Killerspin',23)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (131, now() - interval '1 year 7 months','Nittaku',23)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (132, now() - interval '0 year 5 months','Sportcraft',1)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (133, now() - interval '1 year 8 months','Donic',1)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (134, now() - interval '0 year 6 months','Stiga',1)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (135, now() - interval '1 year 2 months','DHS',2)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (136, now() - interval '0 year 1 months','Donic',2)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (137, now() - interval '1 year 10 months','Tibhar',2)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (138, now() - interval '0 year 11 months','Andro',2)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (139, now() - interval '0 year 5 months','Friendship',3)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (140, now() - interval '1 year 2 months','Andro',3)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (141, now() - interval '1 year 2 months','Friendship',3)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (142, now() - interval '0 year 8 months','DMI',4)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (143, now() - interval '1 year 11 months','DHS',4)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (144, now() - interval '0 year 1 months','Tibhar',4)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (145, now() - interval '1 year 2 months','DMI',5)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (146, now() - interval '0 year 10 months','Butterfly',5)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (147, now() - interval '1 year 5 months','Sportcraft',5)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (148, now() - interval '0 year 9 months','Yasaka',5)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (149, now() - interval '1 year 5 months','DHS',5)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (150, now() - interval '1 year 6 months','DHS',5)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (151, now() - interval '1 year 0 months','Butterfly',6)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (152, now() - interval '0 year 1 months','Donic',6)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (153, now() - interval '0 year 6 months','Yasaka',6)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (154, now() - interval '1 year 8 months','Tibhar',6)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (155, now() - interval '0 year 9 months','Yasaka',6)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (156, now() - interval '0 year 10 months','Yinhei',7)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (157, now() - interval '1 year 6 months','DHS',7)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (158, now() - interval '0 year 4 months','Andro',7)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (159, now() - interval '1 year 10 months','Killerspin',7)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (160, now() - interval '1 year 10 months','Sportcraft',8)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (161, now() - interval '1 year 2 months','Andro',8)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (162, now() - interval '1 year 1 months','DHS',8)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (163, now() - interval '0 year 6 months','Tibhar',8)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (164, now() - interval '0 year 11 months','Sportcraft',8)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (165, now() - interval '1 year 3 months','Nittaku',8)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (166, now() - interval '1 year 8 months','Joola',9)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (167, now() - interval '1 year 2 months','Butterfly',9)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (168, now() - interval '1 year 4 months','Sportcraft',9)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (169, now() - interval '0 year 4 months','Yinhei',9)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (170, now() - interval '0 year 10 months','Stiga',10)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (171, now() - interval '0 year 2 months','DHS',10)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (172, now() - interval '0 year 3 months','DHS',10)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (173, now() - interval '1 year 1 months','Stiga',10)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (174, now() - interval '0 year 2 months','Tibhar',10)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (175, now() - interval '1 year 9 months','Andro',10)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (176, now() - interval '1 year 3 months','729',11)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (177, now() - interval '1 year 6 months','Yasaka',11)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (178, now() - interval '1 year 2 months','Joola',11)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (179, now() - interval '0 year 4 months','DMI',11)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (180, now() - interval '1 year 1 months','Nittaku',11)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (181, now() - interval '1 year 4 months','Stiga',11)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (182, now() - interval '0 year 10 months','Killerspin',11)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (183, now() - interval '1 year 7 months','DMI',12)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (184, now() - interval '0 year 7 months','Donic',12)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (185, now() - interval '1 year 0 months','Yinhei',12)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (186, now() - interval '1 year 5 months','DHS',12)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (187, now() - interval '1 year 8 months','Andro',12)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (188, now() - interval '1 year 0 months','Donic',12)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (189, now() - interval '1 year 2 months','Donic',12)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (190, now() - interval '0 year 3 months','Yasaka',13)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (191, now() - interval '0 year 1 months','Yinhei',13)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (192, now() - interval '1 year 3 months','Donic',13)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (193, now() - interval '1 year 4 months','DHS',14)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (194, now() - interval '1 year 3 months','Andro',14)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (195, now() - interval '0 year 4 months','Sportcraft',14)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (196, now() - interval '0 year 11 months','Nittaku',14)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (197, now() - interval '1 year 4 months','Andro',15)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (198, now() - interval '1 year 5 months','Donic',15)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (199, now() - interval '1 year 10 months','Nittaku',15)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (200, now() - interval '0 year 8 months','Joola',16)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (201, now() - interval '0 year 1 months','Sportcraft',16)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (202, now() - interval '1 year 3 months','DMI',16)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (203, now() - interval '0 year 0 months','Butterfly',16)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (204, now() - interval '1 year 5 months','Yinhei',17)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (205, now() - interval '1 year 1 months','Tibhar',17)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (206, now() - interval '0 year 2 months','Stiga',17)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (207, now() - interval '0 year 0 months','Sportcraft',17)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (208, now() - interval '1 year 10 months','Nittaku',17)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (209, now() - interval '1 year 0 months','Yinhei',17)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (210, now() - interval '1 year 0 months','Friendship',17)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (211, now() - interval '1 year 8 months','Tibhar',17)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (212, now() - interval '1 year 9 months','729',17)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (213, now() - interval '1 year 9 months','Yasaka',17)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (214, now() - interval '1 year 11 months','Sportcraft',18)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (215, now() - interval '1 year 4 months','DMI',18)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (216, now() - interval '1 year 4 months','Killerspin',18)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (217, now() - interval '1 year 11 months','Butterfly',18)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (218, now() - interval '0 year 5 months','Butterfly',19)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (219, now() - interval '0 year 6 months','Killerspin',19)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (220, now() - interval '1 year 1 months','Friendship',19)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (221, now() - interval '1 year 0 months','DMI',19)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (222, now() - interval '1 year 2 months','Tibhar',19)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (223, now() - interval '1 year 10 months','729',23)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (224, now() - interval '1 year 7 months','Killerspin',23)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (225, now() - interval '1 year 1 months','Butterfly',23)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (226, now() - interval '0 year 4 months','Stiga',23)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (227, now() - interval '0 year 6 months','Butterfly',23)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (228, now() - interval '0 year 1 months','Sportcraft',23)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (229, now() - interval '1 year 5 months','Nittaku',23)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (230, now() - interval '1 year 8 months','Tibhar',23)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (231, now() - interval '1 year 3 months','Friendship',23)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (232, now() - interval '1 year 2 months','Nittaku',22)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (233, now() - interval '0 year 8 months','Donic',22)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (234, now() - interval '1 year 6 months','Nittaku',22)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (235, now() - interval '1 year 6 months','Nittaku',21)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (236, now() - interval '1 year 4 months','Nittaku',21)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (237, now() - interval '0 year 9 months','Yinhei',21)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (238, now() - interval '0 year 0 months','729',21)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (239, now() - interval '1 year 10 months','Sportcraft',21)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (240, now() - interval '0 year 1 months','Killerspin',20)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (241, now() - interval '1 year 0 months','DHS',20)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (242, now() - interval '0 year 4 months','Friendship',1)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (243, now() - interval '0 year 6 months','Joola',1)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (244, now() - interval '1 year 8 months','Donic',1)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (245, now() - interval '1 year 9 months','Friendship',1)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (246, now() - interval '1 year 4 months','Donic',1)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (247, now() - interval '0 year 0 months','Yinhei',3)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (248, now() - interval '1 year 1 months','Sportcraft',3)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (249, now() - interval '0 year 10 months','DHS',3)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (250, now() - interval '1 year 10 months','Yinhei',3)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (251, now() - interval '0 year 9 months','Donic',3)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (252, now() - interval '0 year 9 months','Yinhei',6)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (253, now() - interval '0 year 4 months','Yinhei',6)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (254, now() - interval '0 year 5 months','DHS',6)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (255, now() - interval '0 year 9 months','Yinhei',6)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (256, now() - interval '1 year 1 months','Sportcraft',6)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (257, now() - interval '0 year 6 months','Friendship',7)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (259, now() - interval '0 year 8 months','DHS',7)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (260, now() - interval '0 year 6 months','Donic',7)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (261, now() - interval '0 year 9 months','Donic',8)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (262, now() - interval '1 year 0 months','Tibhar',8)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (265, now() - interval '1 year 2 months','Sportcraft',8)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (266, now() - interval '0 year 1 months','DHS',8)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (267, now() - interval '1 year 4 months','Joola',9)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (268, now() - interval '1 year 6 months','Andro',9)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (269, now() - interval '1 year 8 months','Sportcraft',9)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (270, now() - interval '1 year 1 months','Butterfly',9)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (272, now() - interval '1 year 0 months','DHS',10)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (273, now() - interval '1 year 0 months','Killerspin',10)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (274, now() - interval '1 year 11 months','Yinhei',10)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (275, now() - interval '1 year 4 months','Joola',10)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (276, now() - interval '0 year 5 months','Joola',11)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (280, now() - interval '1 year 5 months','Yasaka',11)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (281, now() - interval '1 year 8 months','DMI',11)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (282, now() - interval '0 year 9 months','Killerspin',11)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (283, now() - interval '0 year 3 months','Donic',12)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (284, now() - interval '1 year 1 months','Andro',12)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (285, now() - interval '1 year 6 months','Andro',12)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (286, now() - interval '1 year 3 months','Tibhar',12)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (288, now() - interval '0 year 1 months','Killerspin',13)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (289, now() - interval '1 year 5 months','Yasaka',13)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (290, now() - interval '1 year 11 months','Stiga',13)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (291, now() - interval '1 year 8 months','Andro',14)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (292, now() - interval '0 year 0 months','Yinhei',14)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (293, now() - interval '1 year 10 months','729',14)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (294, now() - interval '1 year 8 months','Butterfly',14)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (297, now() - interval '0 year 1 months','Friendship',15)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (298, now() - interval '0 year 9 months','Yinhei',15)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (300, now() - interval '0 year 3 months','Yinhei',15)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (301, now() - interval '0 year 11 months','Killerspin',15)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (302, now() - interval '1 year 2 months','Donic',16)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (303, now() - interval '0 year 11 months','Sportcraft',16)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (304, now() - interval '1 year 11 months','DHS',16)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (308, now() - interval '0 year 7 months','Yasaka',16)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (309, now() - interval '0 year 8 months','Nittaku',17)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (310, now() - interval '0 year 1 months','Yinhei',17)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (311, now() - interval '1 year 10 months','DHS',17)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (312, now() - interval '0 year 3 months','Andro',17)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (313, now() - interval '1 year 7 months','Stiga',18)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (314, now() - interval '0 year 8 months','Nittaku',18)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (315, now() - interval '1 year 4 months','Friendship',18)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (316, now() - interval '0 year 4 months','Yasaka',18)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (317, now() - interval '1 year 2 months','Butterfly',19)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (318, now() - interval '1 year 5 months','Andro',19)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (319, now() - interval '0 year 4 months','Stiga',19)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (320, now() - interval '1 year 1 months','DMI',19)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (321, now() - interval '1 year 5 months','Stiga',19)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (322, now() - interval '0 year 7 months','Andro',20)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (323, now() - interval '0 year 0 months','Stiga',20)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (324, now() - interval '1 year 0 months','Yinhei',20)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (325, now() - interval '0 year 5 months','Yinhei',20)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (326, now() - interval '1 year 8 months','DMI',20)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (327, now() - interval '0 year 9 months','Yinhei',21)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (328, now() - interval '0 year 8 months','Stiga',21)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (329, now() - interval '0 year 7 months','Butterfly',21)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (330, now() - interval '1 year 1 months','Tibhar',21)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (331, now() - interval '0 year 7 months','729',21)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (332, now() - interval '0 year 10 months','Joola',21)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (333, now() - interval '0 year 4 months','729',21)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (335, now() - interval '0 year 4 months','Yinhei',22)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (336, now() - interval '1 year 3 months','Nittaku',22)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (337, now() - interval '0 year 6 months','DMI',22)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (338, now() - interval '0 year 2 months','DHS',22)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (339, now() - interval '1 year 11 months','Killerspin',22)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (340, now() - interval '1 year 4 months','Friendship',22)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (341, now() - interval '0 year 2 months','Yinhei',22)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (342, now() - interval '0 year 11 months','Stiga',22)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (343, now() - interval '0 year 10 months','Sportcraft',22)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (344, now() - interval '1 year 9 months','Stiga',23)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (345, now() - interval '1 year 9 months','729',23)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (347, now() - interval '1 year 3 months','Killerspin',23)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (348, now() - interval '1 year 2 months','DHS',23)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (349, now() - interval '0 year 0 months','Donic',23)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (350, now() - interval '0 year 10 months','DMI',23)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (351, now() - interval '1 year 4 months','Butterfly',23)
insert into igrachi(id_lice_igrach,posleden_lekarski_pregled,opis_na_reket,id_tim) values (352, now() - interval '1 year 9 months','Yasaka',23)

insert into Natprevari(data_odigran,id_tim_domakjin,id_tim_gostin,id_sala) values(now() - interval '3 months',1,2,4)
insert into Natprevari(data_odigran,id_tim_domakjin,id_tim_gostin,id_sala) values(now() - interval '3 months 7 days',3,2,4)
insert into Natprevari(data_odigran,id_tim_domakjin,id_tim_gostin,id_sala) values(now() - interval '3 months 7 days',3,5,3)

insert into mechevi(id_lice_igrach_domakjin,id_lice_igrach_gostin,lice_id_sudija,faza_id_turnir,faza_id_kategorija,faza_reden_broj,dobieni_setovi_domakjin,dobieni_setovi_gostin)
values(1,3,1,3,1,16,0,3),
	(4,5,10,3,1,16,1,3),
	(7,8,1,3,1,16,3,1),
	(9,12,1,3,1,16,0,3),
	(13,14,1,3,1,16,3,0),
	(15,16,1,3,1,16,3,1),
	(17,18,1,3,1,16,0,3),
	(19,20,1,3,1,16,0,3)
insert into mechevi(id_lice_igrach_domakjin,id_lice_igrach_gostin,lice_id_sudija,faza_id_turnir,faza_id_kategorija,faza_reden_broj,dobieni_setovi_domakjin,dobieni_setovi_gostin)
values(3,5,100,3,1,14,3,0),
(7,12,50,3,1,14,3,2),
(13,15,100,3,1,14,3,2),
(18,20,50,3,1,14,2,3)
insert into mechevi(id_lice_igrach_domakjin,id_lice_igrach_gostin,lice_id_sudija,faza_id_turnir,faza_id_kategorija,faza_reden_broj,dobieni_setovi_domakjin,dobieni_setovi_gostin)
values(3,7,100,3,1,12,3,0),
(13,20,50,3,1,12,3,2)
insert into mechevi(id_lice_igrach_domakjin,id_lice_igrach_gostin,lice_id_sudija,faza_id_turnir,faza_id_kategorija,faza_reden_broj,dobieni_setovi_domakjin,dobieni_setovi_gostin)
values(3,13,100,3,1,11,3,1)

insert into setovi(id_mech,poeni_domakjin,poeni_gostin)
values(29,5,11),(29,4,11),(29,2,11),
(30,6,11),(30,7,11),(30,11,9),(30,8,11),
(31,11,5),(31,11,5),(31,11,6),(31,11,8),
(32,2,11),(32,5,11),(32,8,11),
(33,11,5),(33,11,5),(33,11,6),
(34,11,2),(34,11,6),(33,8,11),(33,11,8),
(35,2,11),(35,3,11),(35,2,11),
(36,7,11),(36,4,11),(36,6,11)
insert into setovi(id_mech,poeni_domakjin,poeni_gostin)
values(38,11,5),(38,11,6),(38,11,2),
(39,11,5),(39,6,11),(39,11,8),(39,8,11),(39,20,18),
(40,4,11),(40,6,11),(40,11,9),(40,11,8),(40,11,9),
(41,11,9),(41,8,11),(41,11,7),(41,9,11),(41,11,8)
insert into setovi(id_mech,poeni_domakjin,poeni_gostin)
values(42,11,5),(42,11,7),(42,11,6),
(43,11,6),(43,11,9),(43,7,11),(43,9,11),(43,11,9)
insert into setovi(id_mech,poeni_domakjin,poeni_gostin)
values(44,9,11),(44,11,5),(44,11,4),(44,11,7)

insert into spagja(id_liga, id_sezona, id_tim, tim_poeni)
values (5, 1, 6, 12),(5, 1, 7, 11),(5, 1, 8, 10),(5, 1, 1, 9),
(5, 1, 2, 8),(5, 1, 3, 7),(5, 1, 4, 6),(5, 1, 5, 5),
(6, 2, 1, 5),(6, 2, 2, 6),(6, 2, 3, 7),(6, 2, 4, 11),
(6, 2, 5, 12),(6, 2, 6, 10),(6, 2, 7, 9),(6, 2, 8, 8),
(1, 3, 1, 5),(1, 3, 2, 6),(1, 3, 3, 7),(1, 3, 4, 11),
(1, 3, 5, 12),(1, 3, 6, 10),(1, 3, 7, 9),(1, 3, 8, 8)